import React from "react";
import './privacy-policy.css';
import MyHeader from '../../components/header/header';
import MyFooter from '../../components/footer/footer';

function PrivacyPolicy(){
    return(
        <div className="privacy-policypage">
            <MyHeader />
            <div className="policy">
                <div className="head container">
                    <h1>Privacy Policy</h1>
                </div>
            </div>
            <div className="policy-body container">
                <h2>Privacy Policy</h2>
                <p>This Privacy Policy, together with our Terms of Use and its other essential parts, governs NCX’s collection, 
                    processing and use of your Personal Data. As used in this Privacy Policy, “NCX“, “we“, “us” or “our” refers 
                    to NCX Digital Exchange LLC, a company duly incorporated and validly existing under the laws of St. Vincent 
                    and the Grenadines, Company Reg. Number - 2477 LLC 2022, with the registered Address - Suite 305, Griffith 
                    Corporate Centre, Beachmont, Kingstown, St. Vincent and the Grenadines. NCX is a data controller under this 
                    Privacy Policy, which sets out the manner in which a company, as a data controller, may use your Personal Data.</p>
                <p>NCX and its Affiliates undertake maximum efforts in order to protect your privacy. NCX uses the collected 
                    information about you to fulfill its contractual obligations and improve customer service.</p>
                <p>Please read this document carefully in order to understand our approach and policy regarding your Personal 
                    Data and how we will use your Personal Data.</p>
                <h3>1. WHAT DATA WE COLLECT ABOUT YOU</h3>
                <p>We may collect and process the following data about you:</p>
                <p>Information you give to us</p>
                <p>You can provide us with information about yourself by filling in the relevant forms on the Website or by 
                    providing us such information by phone, email, during a video conference or in any other manner. This 
                    information includes Personal Data which was specified when registering on the Website, when subscribing to 
                    our Service, opening an Account and verifying the identity of the Account holder or persons authorized to use 
                    it, as well as the payment instruments used by a person, when searching for a product, using any of Services 
                    provided by our Website, while placing Orders on our Website, by participating in discussions in Chat or using 
                    any other communication functions on our Website, during participation in draws, promotions or surveys, and 
                    also when you tell us about problems or issues in the work of the Website.</p>
                <p>For example, the data that you provide to us, may include your:</p>  
                <ul>
                    <li>last name and first name;</li>
                    <li>photos and videos that you may send to us for AML/CTF and KYC Policy verification purposes;</li>
                    <li>residential address and citizenship;</li>
                    <li>gender;</li>
                    <li>passport, driver’s license or any other government-issued ID;</li>
                    <li>tax residency;</li>
                    <li>phone number and email address;</li>
                    <li>login information and nickname for accessing NCX Platform;</li>
                    <li>bank details, including account numbers and payment details, and FATCA/CRS information;</li>
                    <li>date and place of birth;</li>
                    <li>education;</li>
                    <li>work experience and place of work;</li>
                    <li>PEP (politically exposed person) status</li>
                    <li>sources and amount of income and/or Account Top-Ups;</li>
                    <li>information on the status of your accounts opened with banks and/or payment systems;</li>
                    <li>inquiries with NCX support;</li>
                    <li>trading balances and activity;</li>
                    <li>location and log data information that is generated by your use of NCX Platform;</li>
                    <li>other personal information that may be required by our AML/CTF and KYC Policy compliance obligations.</li>
                </ul>
                <p>NCX does not collect nor process sensitive personal Users’ data, such as race or ethnic origin, political 
                    opinions, religious or philosophical beliefs, trade union memberships, genetic or biometric data, health, 
                    sex life or sexual orientation information. However, we caution you that in case you disclose any information 
                    in the public Chat on our Website, it can be collected by persons or companies NCX has no control over.</p>
                <p>Information we collect about you</p>
                <p>With regard to each of your visits to our Website and use of our Services we can collect, for example, the 
                    following information about you (including automatic collection):</p>
                <ul>
                    <li>technical information, including the internet protocol (IP) address used to connect your computer to the internet, your Account login information, your browser type and its version, time zone setting, browser plug-in types and versions, operating system and platform;</li>
                    <li>information about your visit, including the full Uniform Resource Locators (URL) clickstream to, through and from our Website (including date and time); products and Services you viewed or searched for; page response times, download errors, length of visits to certain pages, page interaction information (such as scrolling, clicks, and mouse-overs), and methods used to browse away from the page and any phone number used to call our customer service number;</li>
                    <li>information about geo-location: we may collect information about real-time location based on information from your device at any time while you download or use our services; we may use this information to optimize your experience.</li>
                    <li>financial data and information on the use of Services and facilities provided by our Website, including information on implemented transactions and parties thereto, including on transactions, information on the status of Accounts and cash flow on them, accrued commissions, information on Account Top-Ups and Withdrawal of Funds from Accounts opened on our Platform.</li>
                </ul>
                <p>Information we receive from other sources</p>
                <p>We may receive information about you if you use any of the other Websites we operate or the other services we provide. We are also working closely with third parties (including, for example, business partners, sub-contractors in technical, payment and delivery services, advertising networks, analytics providers, due diligence providers, credit reference agencies) and may receive information about you from them. Such information may include:</p>
                <ol>
                    <li>information about financial institutions you employ to perform Account Top-Ups and/or Withdrawal of Funds;</li>
                    <li>credit agencies’ confirmation of information that you have provided to us;</li>
                    <li>information about your financial standing, name and/or address that may be provided to us by third parties we collaborate with.</li>
                </ol>
                        
                <p>Your Personal Data, such as your email and nickname, that you provide to us during the registration at the NCX Platform is stored by us, regardless of whether your registration process is finished or not. The same is applied to your Personal Data during an unfinished AML/CTF and KYC Policy verification process.</p>
                        
                <h3>2. WHY WE USE YOUR PERSONAL DATA</h3>

                <p>We are going to use your Personal Data for the following purposes:</p>
                
                <p>Provision of our Services</p>

                <ul>
                    <li>to fulfill the obligations under contracts signed with you, as well as to provide you with the information, products and Services that you requested;</li>
                    <li>to ensure the security of our Website, our Services, and your Account;</li>
                    <li>for administration of our Website and for internal operations, including troubleshooting, data analysis, testing, statistical data collection and for conducting surveys;</li>
                    <li>to give you access to the interactive features of the Website in case you wish to use them;</li>
                    <li>to support, respond and resolve your complaints and issues related to the use of our Services and the capabilities of our Website.</li>
                </ul>
                        
                <p>Informing you about our products and Services</p>

                <ul>
                    <li>to notify you about other existing and/or new products and Services, similar to those products or Services that you already purchased or information that you searched for;</li>
                    <li>to notify you about changes related to our products and Services.</li>
                </ul>
                        
                <p>Helping us improve our products and Services</p>
                        
                <ul>
                    <li>to improve our Website and to make sure that our content is most convenient for the operating system of your computer;</li>
                    <li>to evaluate and understand the effectiveness of promotional materials that we provide to you and other Users, as well as to provide you with the necessary advertising information;</li>
                    <li>to ensure the most effective presentation of the content of our Website to you and the use of it on your computer.</li>
                </ul>
                        
                <p>Safeguarding vested interests</p>
                        
                <ul>
                    <li>for risk management;</li>
                    <li>for security and control of our IT systems, crime prevention;</li>
                    <li>for measuring the use of our Services and products for its further development;</li>
                    <li>for internal business and research purposes, i.e. communication with you regarding our products and Services;</li>
                    <li>for anonymized data analysis via web beacons and pixel tags to ensure our products and Services are relevant for the market we operate on.</li>
                </ul>
                        
                <p>Assuring legal procedures</p>
                        
                <ul>
                    <li>to respond to law enforcement requests;</li>
                    <li>to initiate and/or respond to legal claims;</li>
                    <li>to investigate and/or settle disputes with you.</li>
                </ul>
                        
                <p>Complying with legal regulations</p>
                        
                <ul>
                    <li>to verify and check the identity of Users who open and operate Accounts in order to prevent fraud and associated illegal activities;</li>
                    <li>to comply with legal requirements of our AML/CTF and KYC Policy as well as other relevant laws and regulations;</li>
                    <li>to notify our Users about changes to policies and terms of use of NCX Platform.</li>
                </ul>
                        
                <p>Marketing and third parties</p>
                        
                <ul>
                    <li>to provide you with the information about new products or services introduced by NCX or our third party providers, which in our opinion, might be of interest to you; if you are already a User, we will contact you via electronic means of communication (via email or SMS) to inform you about products or services similar to those that were subject of offers or promotions in the past; if you are a new User, we will request your consent to share your Personal Data with other service providers to offer products and services; if you do not want us to use your Personal Data in this way or transfer it to third parties for marketing purposes, please tick the appropriate box on the form used to collect your Personal Data.</li>
                </ul>

                <h3>3. DISCLOSURE OF YOUR PERSONAL DATA</h3>

                <p>We may share your personal information within NCX Group, which includes our subsidiaries, affiliates, our ultimate holding company and its subsidiaries.</p>
                        
                <p>We may share your information with selected third parties including:</p>
                        
                <ul>
                    <li>business partners, suppliers, subcontractors, service providers performing relevant credit and due diligence checks to fulfill contractual obligations we enter into with them or you;</li>
                    <li>marketing networks that require certain data to select and promote relevant adverts; we do not disclose sensitive information about our clients to marketing companies, but we may provide them with aggregate information about our Users (for example, we may inform them that 500 females aged under 30 have clicked on their advertisement on any given day); we may also use such aggregated information to help marketing companies reach the kind of audience they want to target (for example, women, living in a particular region); we may make use of the Personal Data we have collected from you to enable us to comply with our advertisers’ wishes by displaying their advertisement to a specific target audience;</li>
                    <li>analytics and search engine providers that assist us in the improvement and optimization of our Website.</li>
                </ul>
                        
                <p>We may also disclose your Personal Data to third parties in the following cases:</p>
                        
                <ul>
                    <li>if we sell or buy any business or assets; Personal Data of Users may be disclosed to a potential buyer or seller;</li>
                    <li>if NCX or all of its assets are purchased by a third party, Personal Data of Users will be transferred as one of the assets’ form;</li>
                    <li>if we are required to disclose or transfer Personal Data of the User in accordance with any applicable laws or within the implementation of decisions of the relevant courts, requests of judicial and law enforcement authorities or we are compelled to force Users to comply with the terms and conditions of the agreements signed with us;</li>
                    <li>in case it is necessary to protect our rights, property or to guarantee the safety of NCX, our Users or others; this includes the exchange of information with relevant organizations to prevent fraud and reduce the likelihood of default.</li>
                </ul>

                <h3>4. SECURITY AND STORAGE OF PERSONAL DATA</h3>

                <p>We have implemented security measures to ensure the confidentiality of your Personal Data and to protect it from loss, misuse, alteration or destruction. Only authorized personnel of NCX have access to your Personal Data, and this personnel is required to treat the information as confidential. Security measures in place will, from time to time, be reviewed in line with legal and technical developments.</p>
                        
                <p>The information we receive from you can be transferred and stored outside the European Economic Area (“EEA“) for the purposes of providing you with our Services. The information about you can be processed by our employees or employees of service providers outside the EEA. When storing or otherwise processing your Personal Data by such third parties outside the EEA, we guarantee that we will notify such third parties of our obligations under this Privacy Policy and will enter with them into relations that will impose obligations for them regarding your Personal Data, provided that they have the relevant level of security as specified in this Privacy Policy. Such employees, among other things, can process your requests, payment details and provide technical support. By giving us your Personal Data, you consent to the transfer, storage and processing of your Personal Data. We, in turn, will take all necessary measures to ensure that your Personal Data is processed in compliance with international security standards and in accordance with the provisions of this Privacy Policy.</p>
                        
                <p>Whilst the transmission of information via the internet is not completely secure, we will endeavor to protect your Personal Data. With this in mind, we cannot, however, guarantee the security of the channels you will use to transfer your personal information to our Website. In this regard, you are solely responsible for possible failures in the transfer of your Personal Data to the Website. Once we have received your Personal Data, we will use strict procedures and all necessary technical and security measures to prevent unauthorized access to your Personal Data.</p>

                <h3>5. BASIS FOR PERSONAL DATA PROCESSING</h3>

                <p>We collect and process your Personal Data only when we have a legitimate reason for such processing. Legal grounds may include:</p>

                <ul>
                    <li>your consent;</li>
                    <li>an agreement, where processing is necessary to fulfill the terms and conditions of the agreement between you and NCX;</li>
                    <li>compliance with legal obligations, where NCX is required to request/receive and process, as well as store your Personal Data in order to comply with the requirements of applicable laws, for example, the laws related to anti-money laundering and counter-terrorist financing;</li>
                    <li>to use legitimate interest, for example, when processing is necessary to protect you or us from certain threats, such as fraud, security threats, etc.;</li>
                    <li>to comply with the provisions of applicable laws, in order to conduct our business (the quality of the services provided, identification of needs, preparation of reports) in line with regulatory requirements;</li>
                    <li>execution of corporate transactions (sale of participant interests/shares, mergers, acquisitions), etc.</li>
                </ul>

                <p>In cases where the basis for Personal Data processing is your consent, you have the right to withdraw it at any time.</p>


                <h3>6. YOUR RIGHTS</h3>

                <p>By contacting us you can use the following rights:</p>
                        
                <ul>
                    <li>the right to delete your Personal Data (all or part thereof, considering, however, our regulatory requirements to retain your personal data as set forth in Clause 9 of this Privacy Policy);</li>
                    <li>the right to change or correct your Personal Data, in particular when it is incorrectly stated;</li>
                    <li>the right to object or restrict processing of your Personal Data;</li>
                    <li>the right to access to your Personal Data and/or copy of your Personal Data, which you have provided to NCX, in a machine-readable format.</li>
                </ul>
                        
                <p>In addition, you have the right to prohibit the use of your Data for marketing purposes. Before requesting your Data, we usually request your consent to disclose it to third parties for marketing purposes. You can use the right to prohibit the processing of your Data for marketing purposes by putting a tick in the relevant field in the questionnaire. You can also exercise this right by contacting us at any time.</p>
                        
                <p>Please note that the implementation of some of your rights, depending on the situation, may limit, complicate or completely exclude the possibility of further cooperation with us.</p>
                        
                <p>Our Website may contain active links from/to the websites of our partners, advertisers and Affiliated companies. If you are following an active link, please note that other websites have their own privacy policies, and we are not responsible for the provisions of these policies. Please review the privacy policies of these websites before sharing your Personal Data with them.</p>
                        
                <h3>7. RETENTION OF PERSONAL DATA</h3>
                        
                <p>Making sure your Personal Data is safe and secured is of the highest priority to us. We use secure storage facilities ensuring the safeguard of your Personal Data you share with us at all stages of interaction with our Platform using our products and Services. All appropriate measures to secure your Personal Data from potential hacking attacks, loss or misuse are implemented by our security team.</p>
                        
                <p>We will hold your Personal Data only for the duration of you using our products and Services via your Account, having regard to the purposes described in this Privacy Policy as well as legal and regulatory obligations that we comply with. In accordance with our record keeping obligations, we will retain your Account information and your Personal Data for at least a period of 5 (five) years from the moment you cease to carry on the use of our Services or the moment you end of your client relationship with us unless otherwise required for legal or regulatory reasons.</p>
                        
                <p>We may access your Personal Data or retain it for a longer period if it will be subject to an official request or legal obligation, an investigation by governmental bodies or investigation into possible violations of our User Agreement and its essential parts, or in other cases to prevent possible harm based on our reasonable considerations.</p>
                        
                <p>If you will cancel your subscription to our email newsletter, we will hold your email on an inactive email list.</p>
                        
                <h3>8. CHANGES TO THIS PRIVACY POLICY</h3>
                        
                <p>Any changes we may make to our Privacy Policy in the future will be posted on this page and, where appropriate, a notification will be sent to you by email. We encourage you to check this page frequently to be aware of any updates or changes to the Privacy Policy.</p>
                        
                <h3>9. CONTACT</h3>
                        
                <p>In accordance with the Data Protection Act 2018 and ePrivacy Directive 2009/136/EC, in case you will have any questions, complaints or concerns regarding our Privacy Policy, Cookie Policy or the way or purpose for which we handle your Personal Data — you can contact us. For that purpose, please contact our Data Protection Officer via email legal@ncx.cx </p>
            </div>
            <MyFooter />
        </div>
    )
}

export default PrivacyPolicy;