const carddata = [
    {
      id: 1,
      img: 'https://ncx.cx/ncx-whitecard.png',
      title: <h1>NCX <span>Select</span></h1>,
      point1: <p>Monthly Limit<span>$10,000</span></p>,
      point2: <p>ATM Withdrawals<span>$2,500 Monthly</span></p>,
      point3: <p>Free Premium Metal Card</p>,
      point4: <p>24/7 Support</p>,
      point5: <p>Trading Fee Discount<span>0%</span></p>,
      point6: <p>Top-Up By Crypto</p>,
      point7: <p>Virtual Card</p>,
      point8: <p>0.5% Wire Transfer</p>,
      point9: <p>Card Security Features</p>,
      point10: <p>Apple Pay, Google Pay, Samsung Pay</p>,
    },
    {
        id: 2,
        img: 'https://ncx.cx/ncx-platniumcard.png',
        title: <div><h1>NCX <span>Platinum</span></h1></div>,
        point1: <p>Monthly Limit<span>$25,000</span></p>,
        point2: <p>ATM Withdrawals<span>$5,000 Monthly</span></p>,
        point3: <p>Trading Fee Discount<span>10%</span></p>,
        point4: <p>Free Wire Transfer</p>,
        point5: <p>Free Premium Metal Card</p>,
        point6: <p>Top-Up By Crypto</p>,
        point7: <p>Virtual Card</p>,
        point8: <p>Card Security Features</p>,
        point9: <p>24/7 Support</p>,
        point10: <p>Apple Pay, Google Pay, Samsung Pay</p>,
      },
      {
        id: 3,
        img: 'https://ncx.cx/ncx-whitegoldcard.png',
        title: <div><h1>NCX <span>Gold</span></h1></div>,
        point1: <p>Monthly Limit<span>$50,000</span></p>,
        point2: <p>ATM Withdrawals<span>$10,000 Monthly</span></p>,
        point3: <p>Trading Fee Discount<span>15%</span></p>,
        point4: <p>Free Premium Metal Card</p>,
        point5: <p>10% Discount on<span>Booking.com</span></p>,
        point6: <p>Top-Up By Crypto</p>,
        point7: <p>Virtual Card</p>,
        point8: <p>Free Wire Transfer</p>,
        point9: <p>Card Security Features</p>,
        point10: <p>24/7 Support</p>,
        point11: <p>Apple Pay, Google Pay, Samsung Pay</p>,
      },
      {
        id: 4,
        img: 'https://ncx.cx/ncx-blackcard.png',
        title: <div><h1>NCX <span>Black</span></h1></div>,
        point1: <p>Monthly Limit<span>$100,000</span></p>,
        point2: <p>ATM Withdrawals<span>$15,000 Monthly</span></p>,
        point3: <p>Trading Fee Discount<span>20%</span></p>,
        point4: <p>Free<span>Spotify</span>Subscription</p>,
        point5: <p>10% Discount on<span>Expedia.com</span></p>,
        point6: <p>10% Discount on <span>Booking.com</span></p>,
        point7: <p>Free Premium Metal Card</p>,
        point8: <p>Free Wire Transfer</p>,
        point9: <p>Airport Lounge Acces</p>,
        point10: <p>Card Security Features</p>,
        point11: <p>Virtual Card</p>,
        point12: <p>24/7 Support</p>,
        point13: <p>Apple Pay, Google Pay, Samsung Pay</p>,
        point14: <p>Top-Up By Crypto</p>,
      },
  ];
  
  export default carddata;